"""
File Tool Constants
===================

Centralized constants for file tool behaviors.
"""

KIB = 1024
MIB = 1024 * KIB
GIB = 1024 * MIB

MAX_FILE_BYTES = 1 * GIB
DEFAULT_READ_MAX_BYTES = 5 * MIB
DEFAULT_READ_MAX_TOKENS = 50_000
DEFAULT_IMAGE_MAX_BYTES = 20 * MIB
DEFAULT_PDF_MAX_PAGES = 50
DEFAULT_MAX_CACHE_CONTENT_CHARS = 200_000
BINARY_CHECK_BYTES = 8 * KIB
BINARY_NON_TEXT_RATIO = 0.3
LINE_NUMBER_MIN_WIDTH = 6
LINE_NUMBER_SEPARATOR = " | "
MIN_PDF_PAGE_COUNT = 1
